- name: Install GitLab CE
  hosts: "*"
  become: true
  vars:
    gitlab_domain: "18.223.26.44"
    gitlab_external_url: "http://{{ gitlab_domain }}"
  tasks:

    - name: Mount opt in /dev/nvme1n1
      block:
        - name: Format disk
          ansible.builtin.filesystem:
            fstype: ext4
            dev: /dev/nvme1n1
    
        - name: Create mount point for app data
          ansible.builtin.file:
            path: /opt
            state: directory

        - name: Mount large disk on /opt
          ansible.builtin.mount:
            path: /opt
            src: /dev/nvme1n1
            fstype: ext4
            state: mounted
            opts: defaults
    
    - name: Create a swap file
      block:
        - name: Check if swapfile exists
          ansible.builtin.stat:
            path: /opt/swapfile
          register: swapfile_stat

        - name: Check if swap is active
          ansible.builtin.command: swapon --show=NAME --noheadings
          register: swap_active
          changed_when: false

        - name: allocate swap file
          ansible.builtin.command: fallocate -l 4G /opt/swapfile
          args:
            creates: /opt/swapfile

        - name: chmod
          ansible.builtin.file: 
            path: /opt/swapfile
            mode: '0600'

        - name: mkswap
          ansible.builtin.command: mkswap /opt/swapfile
          when: not swapfile_stat.stat.exists and '"/opt/swapfile" not in swap_active.stdout'
          
        - name: swapon
          ansible.builtin.command: swapon /opt/swapfile
          register: swapon_result
          failed_when: swapon_result.rc != 0 and "busy" not in swapon_result.stderr

        - name: Persist swap in fstab
          ansible.builtin.mount:
            path: swap
            src: /opt/swapfile
            fstype: swap
            opts: defaults
            state: present

    - name: update/upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
          - tzdata
          - perl
          - postfix
        state: present
        update_cache: true
    
    - name: Install GitLab pkg repository
      ansible.builtin.shell:
        curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
      args:
        creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

    - name: Install Gitlab CE
      ansible.builtin.apt:
        name: gitlab-ce
        state: present
      # environment:
        # EXTERNAL_URL: "{{ gitlab_external_url }}"

    - name: Deploy gitlab config
      ansible.builtin.template:
        src: templates/gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: '0600'
      notify: Reconfigure GitLab

  handlers:
    - name: Reconfigure Gitlab
      ansible.builtin.command: gitlab-ctl reconfigure
